name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: Your slack id ex. @johnDoe
  validations:
    required: true
- type: dropdown
  id: urgency
  attributes:
    label: Urgency
    multiple: true
    options:
      - Critical
      - Urgent
      - Normal
 validations:
  required: true
- type: input
  id: team
  attributes:
    label: Team & Project affected
    description: Team or project that you are working on.
    placeholder: For example Merchant Tech, Stores Center.
  validations:
    required: true
- type: textarea
  id: what-happened
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Technological Stack
    description: What version of our library are you running?. In what environment are you using chirimoya?.
    placeholder: v1.0.0 on React v17.0.2.
  validations:
    required: true
- type: textarea
  id: to-reproduce
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior:
    placeholder: Tell us how this happened!
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error      
  validations:
    required: true
- type: input
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
    placeholder: Tell us what you would like to see! 
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add evidence which helps you to explain the problem. 
    placeholder: Tell us how this happened!
    value: |
      Tip: you can drag and drop your image into this text editor (Attach files by dragging & dropping, selecting or pasting them.).  
  validations:
    required: false
- type: textarea
  id: aditional-context
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
    value: Maybe indicate the piece of code that you think is causing the trouble.
  validations:
    required: false
